### ISSUE TITLE
Rename to `css-layout-challenge`

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/css-layout-challenge#4]
Since it's about boxes and flow, not simple styling.

**Comment by berziiii** [comment]
Done @jrhorn424. Also made the change in waffle.

**Comment by payne-chris-r** [comment]
@jrhorn424 @berziiii we can probably close this now. Jeff, you wanna make sure everything looks good here and in waffle? It looks like Brian already made that happen to me.

**Comment by RealWeeks** [comment]
@jrhorn424 bump
